# Generated by Django 5.0.6 on 2024-07-07 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='version',
        ),
    ]
